[build]
  command = "hugo"
  publish = "public/"

[build.environment]
  HUGO_VERSION = "0.152.2"
  NODE_VERSION = "22.13.1"
  AWS_LAMBDA_JS_RUNTIME = "nodejs22.x"
  NETLIFY_USE_JAMMY = "true"

# ####### general ILSA links ####### 

[[redirects]]
  from = "/rules"
  to = "/documents/ILSA%20-%20Rules%20of%20Play%20-%201.1.pdf"
  status = 302

[[redirects]]
  from = "/howtoplay"
  to = "/documents/ILSA%20-%20Rules%20of%20Play%20-%201.1.pdf"
  status = 302
  # now points to full rules, later to lightweight rules

[[redirects]]
  from = "/volunteer"
  to = "https://forms.gle/vYRcQb3JhAdks5cN7"
  status = 302

[[redirects]]
  from = "/l/banner-join"
  to = "/join"
  status = 302

[[redirects]]
  from = "/l/banner-donate"
  to = "/donate"
  status = 302

[[redirects]]
  from = "/l/bio"
  to = "https://lnk.bio/illinoisshuffleboard"
  status = 302

[[redirects]]
  from = "/report-points"
  to = "https://forms.gle/w9HrzHT5M4pikzFZA"
  status = 302

[[redirects]]
  from = "/l/discord"
  to = "https://discord.gg/XUJm3ctWEw"
  status = 302

#  ####### national tournament links ####### 

[[redirects]]
  from = "/lottery"
  to = "https://docs.google.com/spreadsheets/d/1Gi-otAAGUBaqjHzIIM6zJWq4iBHNgxsxeN9GZFikBsc/edit?gid=1237102943#gid=1237102943"
  status = 302
  # now points to 2025 lottery selection google sheet

[[redirects]]
  from = "/lottery-faq"
  to = "https://drive.google.com/file/d/17U6DvWxn6JiykiQfhXXgop9HHJBi-7I-/view?usp=sharing"
  status = 302
  # now points to 2025 pdf

[[redirects]]
  from = "/standings"
  to = "https://docs.google.com/spreadsheets/d/1FAIppioHDaAQNwZwvhCqJrbab_t3Adn5Nyk0LPAoiD0/edit?usp=sharing"
  status = 302
  # now points to 2025 bracket

[[redirects]]
  from = "/national"
  to = "https://lnk.bio/ILLINOISSHUFFLEBOARD"
  status = 302

[[redirects]]
  from = "/nationals"
  to = "/national"
  status = 302

[[redirects]]
  from = "/national-store"
  to = "https://chicago-national-tournament-merchandise.square.site/"
  status = 302

[[redirects]]
  from = "/l/national-badge"
  to = "https://lnk.bio/ILLINOISSHUFFLEBOARD"
  status = 302

[[redirects]]
  from = "/l/national-info"
  to = "https://drive.google.com/file/d/1hv7G3QzCrusnaO3fSdNbOJeTp1CLb1hJ/view"
  status = 302
  # points to 2025 player packet

[[redirects]]
  from = "/l/national-guide"
  to = "https://drive.google.com/file/d/1-5TWvtIUxkeqyxwvwWLlPg9dio_GPqM_/view"
  status = 302
  # points to 2025 chicago guide

[[redirects]]
  from = "/l/national-map"
  to = "https://www.google.com/maps/d/u/0/viewer?mid=18cT5KcCzO3bNkPRdn5Ts4O-XImTGAhI&ll=41.91111613969203%2C-87.67730553778867&z=17"
  status = 302

[[redirects]]
  from = "/l/national-standings"
  to = "https://docs.google.com/spreadsheets/d/1FAIppioHDaAQNwZwvhCqJrbab_t3Adn5Nyk0LPAoiD0/edit?usp=sharing"
  status = 302
  # points to 2025 bracket

[[redirects]]
  from = "/l/national-speed-shuffle"
  to = "https://docs.google.com/forms/d/e/1FAIpQLScN7jhfVne0ffq2n_nszLGh1PeuQwMg74Q28729EkU1_kAMMg/viewform"
  status = 302
  # points to 2025 sign-up form

#  ####### event specific links ####### 

[[redirects]]
  from = "/duck"
  to = "https://app.recrec.io/events/NXDuGB"
  status = 302
  
[[redirects]]
  from = "/garden"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSfw0Ps_Xk3oOkX98somTXErqyv9lLXubDtKRpRnDkM5UaWBGA/viewform"
  status = 302

[[redirects]]
  from = "/shuffle101"
  to = "https://app.recrec.io/seasons/3XNC55/info"
  status = 302
  
#  ####### league links ####### 

[[redirects]]
  from = "/doubles-report"
  to = "https://forms.gle/aTE6fQg1caFgHyN17"
  status = 302
  # points to summer 2025 reporting form

[[redirects]]
  from = "/singles-report"
  to = "https://forms.gle/inaoVH6a1G56kbDB8"
  status = 302
  # points to fall 2025 reporting form

#  ####### other stuff ####### 

[[redirects]]
  from = "/natalie-qr-code"
  to = "https://forms.gle/beVnqPtRe5mm3qfU8"
  status = 302
  # points to natl tournament volunteer signup
